-- AlterTable
ALTER TABLE `memberprofile` ADD COLUMN `clvValue` DOUBLE NOT NULL DEFAULT 0.0,
    ADD COLUMN `rfmScore` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `segment` VARCHAR(191) NOT NULL DEFAULT 'NEW';
